name: k8s-claimer
home: https://github.com/deis/k8s-claimer
version: 0.1.0
description: Allows a user to claim a lease on a kubernetes cluster. Supports GKE and Azure APIs.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
